/**
 * TypeScript mirrors of the backend Pydantic schemas.
 *
 * These types are generated by hand from the FastAPI OpenAPI document
 * (`GET /openapi.json`, `components.schemas`) and must match it EXACTLY —
 * field names, optionality, and `number` vs `string`.
 *
 * Conventions:
 *  - Money / quantity fields are plain `number`s (backend serializes Decimals
 *    as JSON numbers, already rounded).
 *  - Percentages: portfolio/rebalance weights are in *percent units*
 *    (e.g. `40` = 40%); evolution `simple_return`/`twr`/`xirr` are *fractions*
 *    (e.g. `0.12` = 12%).
 *  - `date` fields are ISO dates (`YYYY-MM-DD`); `date-time` fields are ISO 8601.
 */

/* ── Health (HealthResponse) ─────────────────────────────────────────────── */

export interface HealthResponse {
  status: string;
}

/**
 * Standard error envelope surfaced by `client.ts` (`{ "error": "message" }`).
 * Not a backend response model — kept here so the axios error normalizer stays
 * typed.
 */
export interface ErrorResponse {
  error: string;
}

/* ── Positions & allocation (PortfolioView) ──────────────────────────────── */

/**
 * Asset class as classified from the ticker suffix. The backend serializes it
 * as a plain string; common values are "Ação" / "FII" / "ETF" / "BDR".
 */
export type AssetClass = string;

/** One held ticker's valuation row (`Position`). */
export interface Position {
  ticker: string;
  asset_class: AssetClass;
  quantity: number;
  avg_price: number;
  /** Total cost basis invested in this ticker. */
  invested: number;
  /** Latest cached price, or `null` when no quote is available. */
  price: number | null;
  /** ISO date of the quote behind `price`, or `null`. */
  price_date: string | null;
  market_value: number;
  /** Unrealized P&L (market_value − invested). */
  pnl: number;
  pnl_pct: number;
  /** Weight of this position in the portfolio, in percent. */
  weight_pct: number;
  proventos_total: number;
  /** `true` when the price behind this row is stale. */
  stale: boolean;
}

/** Aggregated market value + weight for one asset class (`ClassAllocation`). */
export interface ClassAllocation {
  asset_class: string;
  market_value: number;
  weight_pct: number;
}

/** Portfolio-wide totals (`Totals`). */
export interface Totals {
  invested: number;
  market_value: number;
  pnl: number;
  pnl_pct: number;
  proventos: number;
}

/** Payload for `GET /api/portfolio/positions` (`PortfolioView`). */
export interface PortfolioView {
  /** ISO date of the most recent quote used, or `null` if none. */
  as_of: string | null;
  totals: Totals;
  positions: Position[];
  allocation_by_class: ClassAllocation[];
  message?: string | null;
}

/* ── Evolution & rentability (EvolutionResponse) ─────────────────────────── */

/** One equity-curve point (`EvolutionPointOut`). */
export interface EvolutionPointOut {
  /** ISO date of the snapshot. */
  date: string;
  market_value: number;
  contributions: number;
  proventos: number;
  invested_cost: number;
}

/** Headline return metrics; ratios are fractions (e.g. 0.12 = 12%). */
export interface EvolutionMetrics {
  simple_return: number | null;
  twr: number | null;
  xirr: number | null;
  absolute_gain: number;
}

/** Payload for `GET /api/portfolio/evolution` (backend `EvolutionResponse`). */
export interface EvolutionView {
  points: EvolutionPointOut[];
  metrics: EvolutionMetrics;
  /** ISO date the curve is current to. */
  as_of: string;
}

/** Optional query params for `GET /api/portfolio/evolution`. */
export type EvolutionGranularity = "daily" | "weekly" | "monthly";

export interface EvolutionParams {
  granularity?: EvolutionGranularity;
  from?: string;
  to?: string;
}

/* ── Rebalancing (RebalancePlan) ─────────────────────────────────────────── */

/** One line of the rebalancing plan (`RebalanceRow`). */
export interface RebalanceRow {
  key: string;
  kind: string;
  current_pct: number;
  target_pct: number;
  drift_pct: number;
  current_value: number;
  target_value: number;
  suggested_buy_amount: number;
  suggested_buy_qty: number | null;
  price: number | null;
}

/** Payload for `GET /api/portfolio/rebalance` (backend `RebalancePlan`). */
export interface RebalanceView {
  mode: string;
  contribution: number;
  total_market_value: number;
  rows: RebalanceRow[];
  leftover_cash: number;
  warnings?: string[];
}

/* ── Targets (TargetsResponse / TargetsUpdate) ───────────────────────────── */

/** One stored target — class- or ticker-level (`TargetItem`). */
export interface TargetItem {
  kind: string;
  key: string;
  target_pct: number;
}

/** Back-compat alias for the stored-target shape. */
export type TargetAllocation = TargetItem;

/** Payload for `GET /api/targets` (`TargetsResponse`). */
export interface TargetsResponse {
  class_targets: TargetItem[];
  ticker_targets: TargetItem[];
  warnings?: string[];
}

/** One target row in a `PUT /api/targets` body (`TargetInput`). */
export interface TargetInput {
  key: string;
  target_pct: number;
}

/** Request body for `PUT /api/targets` — replaces all stored targets. */
export interface TargetsUpdate {
  class_targets?: TargetInput[];
  ticker_targets?: TargetInput[];
}

/* ── Accounting — Bens e Direitos (BensEDireitosResponse) ────────────────── */

/**
 * One asset row of the Bens e Direitos preview. The backend passes the legacy
 * dicts through unchanged (Portuguese keys such as "Situação final",
 * "Juros Sobre Capital Próprio"), so the shape is an open string map.
 */
export type AccountingAsset = Record<string, unknown>;

/** An asset whose CNPJ is missing from the catalog (`MissingCnpjItem`). */
export interface MissingCnpjItem {
  Produto: string;
  Grupo: string;
}

/** Payload for `GET /api/accounting/bens-e-direitos` (`BensEDireitosResponse`). */
export interface AccountingView {
  assets: AccountingAsset[];
  missing_cnpj: MissingCnpjItem[];
}

/** One CNPJ override row — POST body item (`CnpjOverrideIn`). */
export interface CnpjOverrideIn {
  Ticker: string;
  Tipo?: string | null;
  CNPJ: string;
}

/** Back-compat alias for a CNPJ override row. */
export type CnpjOverride = CnpjOverrideIn;

/** Result of saving CNPJ overrides (`CnpjOverrideResult`). */
export interface CnpjOverrideResult {
  saved: number;
}

/* ── Ingestion / import (ImportStatus / ImportSummary) ───────────────────── */

/** The `{kind}` path segment accepted by `POST /api/import/{kind}`. */
export type ImportKind = "positions" | "transactions" | "proventos";

/** Row count + latest import timestamp for one ingested table (`TableStatus`). */
export interface TableStatus {
  rows: number;
  /** ISO datetime, or `null` if never imported. */
  last_imported_at?: string | null;
}

/** What data is currently loaded — `GET /api/imports/status` (`ImportStatus`). */
export interface ImportStatus {
  transactions: TableStatus;
  position_summary: TableStatus;
  proventos: TableStatus;
}

/** Result of a single `POST /api/import/{kind}` upload (`ImportSummary`). */
export interface ImportSummary {
  kind: string;
  rows_imported: number;
  tickers: string[];
  warnings: string[];
}

/* ── Quotes (LatestQuote / RefreshResult) ────────────────────────────────── */

/** One ticker's latest price payload (`LatestQuote`). */
export interface LatestQuote {
  price: number;
  /** ISO date of the quote. */
  date: string;
  source: string;
}

/** `GET /api/quotes/latest` — a `{ ticker: LatestQuote }` map. */
export type LatestQuotes = Record<string, LatestQuote>;

/** Result of a forced quote refresh (`RefreshResult`). */
export interface RefreshResult {
  updated: number;
}

/* ── Trades (TradeOut / TradeInput / TradeUpdate) ────────────────────────── */

export type TradeSide = "buy" | "sell";

/** Filter for `GET /api/trades?origin=`. */
export type TradeOrigin = "manual" | "import" | "all";

/** One persisted trade row (`TradeOut`). */
export interface Trade {
  id: number;
  trade_date: string;
  ticker: string;
  market: string;
  side: string;
  quantity: number;
  price: number;
  value: number;
  institution: string | null;
  origin: string;
  note: string | null;
  source_file: string | null;
  /** ISO datetime. */
  imported_at: string;
}

/**
 * Create payload for a manual trade (`TradeInput`). `quantity`/`price` accept a
 * number or a numeric string (the backend coerces); `value` is computed
 * server-side.
 */
export interface TradeInput {
  trade_date: string;
  ticker: string;
  side: TradeSide;
  quantity: number | string;
  price: number | string;
  /** Defaults to "a_vista" server-side. */
  market?: string;
  institution?: string | null;
  note?: string | null;
}

/** Partial edit payload — only provided fields are applied (`TradeUpdate`). */
export interface TradeUpdate {
  trade_date?: string | null;
  ticker?: string | null;
  side?: TradeSide | null;
  quantity?: number | string | null;
  price?: number | string | null;
  market?: string | null;
  institution?: string | null;
  note?: string | null;
}

/** Payload for `GET /api/trades` (`TradeListResponse`). */
export interface TradeListResponse {
  trades: Trade[];
  count: number;
  manual_count: number;
  latest_manual_trade_date: string | null;
}

/** `POST /api/trades/clear-superseded` result (`ClearSupersededResponse`). */
export interface ClearSupersededResponse {
  deleted: number;
}

/* ── Jobs (JobStatus / RunDailyResult) ───────────────────────────────────── */

/** Freshness payload for the dashboard header (backend `JobStatus`). */
export interface JobsStatus {
  /** ISO datetime, or `null`. */
  last_quote_refresh: string | null;
  /** ISO date, or `null`. */
  last_snapshot_date: string | null;
  /** ISO datetime, or `null`; omitted when unknown. */
  next_run?: string | null;
}

/** Outcome of a manual/cron `run-daily` trigger (`RunDailyResult`). */
export interface RunDailyResult {
  quotes_updated: number;
  snapshot_date: string;
  total_value: number | null;
  contributions_to_date: number | null;
  cumulative_proventos: number | null;
}
